# docker compose version that used by this project
version: '3.7'

services:
  # service for the app 
  item-app:
    # image that used 
    image: ghcr.io/mohammad-firmansyah/item-app:v1
    # command to run app
    command: sh -c "npm install --production --unsafe-perm && npm run build"
    # expose host port 80 from docker 8080
    ports:
      - 80:8080
    # workdir app
    working_dir: /app
    # volumes that being used by the app
    volumes:
      - ./:/data/db
    # restart policy 
    restart: always
    # this will not running until item db created
    depends_on:
      - item-db
  # service for database
  item-db:
    # image used
    image: mongo:3
    # volumes that being used 
    volumes:
     - app-db:/data/db
    # restart policy
    restart: always

# making volume 
volumes:
  app-db: